/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  LoginUser400,
  LoginUser401,
  LoginUser500,
  LoginUserMutationRequest,
  LoginUserMutationResponse,
} from '../../__types__/api-v1-auth-login/login-user'
import fetch from '../../api-client/api-client.instance'
import type { Client, RequestConfig, ResponseErrorConfig } from '../../api-client/api-client.instance'

function getLoginUserUrl() {
  const res = { method: 'POST', url: `/api/v1/auth/login` as const }
  return res
}

/**
 * @description Authenticates a user and returns JWT tokens
 * @summary Login user
 * {@link /api/v1/auth/login}
 */
export async function loginUser(
  data: LoginUserMutationRequest,
  config: Partial<RequestConfig<LoginUserMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    LoginUserMutationResponse,
    ResponseErrorConfig<LoginUser400 | LoginUser401 | LoginUser500>,
    LoginUserMutationRequest
  >({ method: 'POST', url: getLoginUserUrl().url.toString(), data: requestData, ...requestConfig })
  return res.data
}