/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from '../error-response'
import type { LoginSuccessResponse } from '../login-success-response'
import type { LoginUserRequest } from '../login-user-request'

/**
 * @description Successfully authenticated
 */
export type LoginUser200 = LoginSuccessResponse

/**
 * @description Invalid request data
 */
export type LoginUser400 = ErrorResponse

/**
 * @description Invalid credentials
 */
export type LoginUser401 = ErrorResponse

/**
 * @description Internal server error
 */
export type LoginUser500 = ErrorResponse

export type LoginUserMutationRequest = LoginUserRequest

export type LoginUserMutationResponse = LoginUser200

export type LoginUserMutation = {
  Response: LoginUser200
  Request: LoginUserMutationRequest
  Errors: LoginUser400 | LoginUser401 | LoginUser500
}
