/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  RequestPasswordReset400,
  RequestPasswordReset404,
  RequestPasswordReset500,
  RequestPasswordResetMutationRequest,
  RequestPasswordResetMutationResponse,
} from '../../__types__/api-v1-auth-request-password-reset/request-password-reset'
import fetch from '../../api-client/api-client.instance'
import type { Client, RequestConfig, ResponseErrorConfig } from '../../api-client/api-client.instance'

function getRequestPasswordResetUrl() {
  const res = { method: 'POST', url: `/api/v1/auth/request-password-reset` as const }
  return res
}

/**
 * @description Initiates password reset by sending an email with reset link
 * @summary Request password reset
 * {@link /api/v1/auth/request-password-reset}
 */
export async function requestPasswordReset(
  data: RequestPasswordResetMutationRequest,
  config: Partial<RequestConfig<RequestPasswordResetMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    RequestPasswordResetMutationResponse,
    ResponseErrorConfig<RequestPasswordReset400 | RequestPasswordReset404 | RequestPasswordReset500>,
    RequestPasswordResetMutationRequest
  >({ method: 'POST', url: getRequestPasswordResetUrl().url.toString(), data: requestData, ...requestConfig })
  return res.data
}
