/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from '../error-response'
import type { MessageSuccessResponse } from '../message-success-response'
import type { ResetPasswordRequest } from '../reset-password-request'

/**
 * @description Password successfully reset
 */
export type ResetPassword200 = MessageSuccessResponse

/**
 * @description Invalid or expired token
 */
export type ResetPassword400 = ErrorResponse

/**
 * @description Internal server error
 */
export type ResetPassword500 = ErrorResponse

export type ResetPasswordMutationRequest = ResetPasswordRequest

export type ResetPasswordMutationResponse = ResetPassword200

export type ResetPasswordMutation = {
  Response: ResetPassword200
  Request: ResetPasswordMutationRequest
  Errors: ResetPassword400 | ResetPassword500
}
