/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  ResetPassword400,
  ResetPassword500,
  ResetPasswordMutationRequest,
  ResetPasswordMutationResponse,
} from '../../__types__/api-v1-auth-reset-password/reset-password'
import fetch from '../../api-client/api-client.instance'
import type { Client, RequestConfig, ResponseErrorConfig } from '../../api-client/api-client.instance'

function getResetPasswordUrl() {
  const res = { method: 'POST', url: `/api/v1/auth/reset-password` as const }
  return res
}

/**
 * @description Completes password reset using a valid token and new password
 * @summary Reset password
 * {@link /api/v1/auth/reset-password}
 */
export async function resetPassword(
  data: ResetPasswordMutationRequest,
  config: Partial<RequestConfig<ResetPasswordMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    ResetPasswordMutationResponse,
    ResponseErrorConfig<ResetPassword400 | ResetPassword500>,
    ResetPasswordMutationRequest
  >({ method: 'POST', url: getResetPasswordUrl().url.toString(), data: requestData, ...requestConfig })
  return res.data
}
