/* eslint-disable no-alert, no-console */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw'

import type {
  LoginUser400,
  LoginUser401,
  LoginUser500,
  LoginUserMutationResponse,
} from '../../__types__/api-v1-auth-login/login-user'

export function loginUserHandlerResponse200(data: LoginUserMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function loginUserHandlerResponse400(data: LoginUser400) {
  return new Response(JSON.stringify(data), {
    status: 400,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function loginUserHandlerResponse401(data: LoginUser401) {
  return new Response(JSON.stringify(data), {
    status: 401,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function loginUserHandlerResponse500(data: LoginUser500) {
  return new Response(JSON.stringify(data), {
    status: 500,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function loginUserHandler(
  data?:
    | LoginUserMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>)
) {
  return http.post(`/api/v1/auth/login`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
