/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type {
  ResetPassword200,
  ResetPassword400,
  ResetPassword500,
  ResetPasswordMutationRequest,
  ResetPasswordMutationResponse,
} from '../../__types__/api-v1-auth-reset-password/reset-password'
import { errorResponseSchema } from '../error-response-schema'
import { messageSuccessResponseSchema } from '../message-success-response-schema'
import { resetPasswordRequestSchema } from '../reset-password-request-schema'

/**
 * @description Password successfully reset
 */
export const resetPassword200Schema = z.lazy(
  () => messageSuccessResponseSchema
) as unknown as z.ZodType<ResetPassword200>

/**
 * @description Invalid or expired token
 */
export const resetPassword400Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<ResetPassword400>

/**
 * @description Internal server error
 */
export const resetPassword500Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<ResetPassword500>

export const resetPasswordMutationRequestSchema = z.lazy(
  () => resetPasswordRequestSchema
) as unknown as z.ZodType<ResetPasswordMutationRequest>

export const resetPasswordMutationResponseSchema = z.lazy(
  () => resetPassword200Schema
) as unknown as z.ZodType<ResetPasswordMutationResponse>
