/* eslint-disable no-alert, no-console */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw'

import type {
  RequestPasswordReset400,
  RequestPasswordReset404,
  RequestPasswordReset500,
  RequestPasswordResetMutationResponse,
} from '../../__types__/api-v1-auth-request-password-reset/request-password-reset'

export function requestPasswordResetHandlerResponse200(data: RequestPasswordResetMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function requestPasswordResetHandlerResponse400(data: RequestPasswordReset400) {
  return new Response(JSON.stringify(data), {
    status: 400,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function requestPasswordResetHandlerResponse404(data: RequestPasswordReset404) {
  return new Response(JSON.stringify(data), {
    status: 404,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function requestPasswordResetHandlerResponse500(data: RequestPasswordReset500) {
  return new Response(JSON.stringify(data), {
    status: 500,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function requestPasswordResetHandler(
  data?:
    | RequestPasswordResetMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>)
) {
  return http.post(`/api/v1/auth/request-password-reset`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
