/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type {
  LoginUser200,
  LoginUser400,
  LoginUser401,
  LoginUser500,
  LoginUserMutationRequest,
  LoginUserMutationResponse,
} from '../../__types__/api-v1-auth-login/login-user'
import { errorResponseSchema } from '../error-response-schema'
import { loginSuccessResponseSchema } from '../login-success-response-schema'
import { loginUserRequestSchema } from '../login-user-request-schema'

/**
 * @description Successfully authenticated
 */
export const loginUser200Schema = z.lazy(() => loginSuccessResponseSchema) as unknown as z.ZodType<LoginUser200>

/**
 * @description Invalid request data
 */
export const loginUser400Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<LoginUser400>

/**
 * @description Invalid credentials
 */
export const loginUser401Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<LoginUser401>

/**
 * @description Internal server error
 */
export const loginUser500Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<LoginUser500>

export const loginUserMutationRequestSchema = z.lazy(
  () => loginUserRequestSchema
) as unknown as z.ZodType<LoginUserMutationRequest>

export const loginUserMutationResponseSchema = z.lazy(
  () => loginUser200Schema
) as unknown as z.ZodType<LoginUserMutationResponse>
