/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface ErrorResponse {
  /**
   * @description Error message describing what went wrong
   * @type string
   */
  message: string
  /**
   * @description HTTP status code
   * @type integer
   */
  status: number
}
