/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TokenPair } from './token-pair'

export interface LoginSuccessResponse {
  /**
   * @description Indicates whether the request was successful
   * @type boolean
   */
  success: boolean
  /**
   * @type object
   */
  data: TokenPair
}
