/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface LoginUserRequest {
  /**
   * @description Email address of the user
   * @type string, email
   */
  email: string
  /**
   * @description User password
   * @minLength 4
   * @maxLength 30
   * @type string
   */
  password: string
}
