/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface MessageSuccessResponse {
  /**
   * @description Indicates whether the request was successful
   * @type boolean
   */
  success: boolean
  /**
   * @description Success message
   * @type string
   */
  data: string
}
