/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface RefreshTokenRequest {
  /**
   * @description Refresh token to generate a new token pair
   * @type string
   */
  refreshToken: string
}
