/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { RegisterUserResponse } from './register-user-response'

export interface RegisterUserSuccessResponse {
  /**
   * @description Indicates whether the request was successful
   * @type boolean
   */
  success: boolean
  /**
   * @type object
   */
  data: RegisterUserResponse
}
