/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface RegisterUserResponse {
  /**
   * @description Unique identifier of the created user
   * @type string, uuid
   */
  id: string
  /**
   * @description Email address of the user
   * @type string, email
   */
  email: string
  /**
   * @description Timestamp when the user was created
   * @type string, date-time
   */
  createdAt: string
  /**
   * @description Timestamp when the user was last updated
   * @type string, date-time
   */
  updatedAt: string
}
