/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface RegisterUserRequest {
  /**
   * @description Email address for the new user account
   * @type string, email
   */
  email: string
  /**
   * @description Password for the new user account (minimum 4 characters, maximum 30 characters)
   * @minLength 4
   * @maxLength 30
   * @type string
   */
  password: string
}
