/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface RequestPasswordResetRequest {
  /**
   * @description Email address to send password reset instructions
   * @type string, email
   */
  email: string
}
