/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface ResetPasswordRequest {
  /**
   * @description Password reset token received via email
   * @type string
   */
  token: string
  /**
   * @description New password for the user account (minimum 4 characters, maximum 30 characters)
   * @minLength 4
   * @maxLength 30
   * @type string
   */
  newPassword: string
}
