/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export interface TokenPair {
  /**
   * @description JWT access token for API authentication
   * @type string
   */
  accessToken: string
  /**
   * @description JWT refresh token for obtaining new access tokens
   * @type string
   */
  refreshToken: string
  /**
   * @description Token type (always \"Bearer\")
   * @type string
   */
  tokenType: string
  /**
   * @description Access token expiration time in seconds
   * @type integer, int64
   */
  expiresIn: number
}
