/* eslint-disable no-alert, no-console */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw'

import type {
  ResetPassword400,
  ResetPassword500,
  ResetPasswordMutationResponse,
} from '../../__types__/api-v1-auth-reset-password/reset-password'

export function resetPasswordHandlerResponse200(data: ResetPasswordMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function resetPasswordHandlerResponse400(data: ResetPassword400) {
  return new Response(JSON.stringify(data), {
    status: 400,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function resetPasswordHandlerResponse500(data: ResetPassword500) {
  return new Response(JSON.stringify(data), {
    status: 500,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function resetPasswordHandler(
  data?:
    | ResetPasswordMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>)
) {
  return http.post(`/api/v1/auth/reset-password`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
