/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type {
  RequestPasswordReset200,
  RequestPasswordReset400,
  RequestPasswordReset404,
  RequestPasswordReset500,
  RequestPasswordResetMutationRequest,
  RequestPasswordResetMutationResponse,
} from '../../__types__/api-v1-auth-request-password-reset/request-password-reset'
import { errorResponseSchema } from '../error-response-schema'
import { messageSuccessResponseSchema } from '../message-success-response-schema'
import { requestPasswordResetRequestSchema } from '../request-password-reset-request-schema'

/**
 * @description Password reset email sent
 */
export const requestPasswordReset200Schema = z.lazy(
  () => messageSuccessResponseSchema
) as unknown as z.ZodType<RequestPasswordReset200>

/**
 * @description Invalid request data
 */
export const requestPasswordReset400Schema = z.lazy(
  () => errorResponseSchema
) as unknown as z.ZodType<RequestPasswordReset400>

/**
 * @description User not found
 */
export const requestPasswordReset404Schema = z.lazy(
  () => errorResponseSchema
) as unknown as z.ZodType<RequestPasswordReset404>

/**
 * @description Internal server error
 */
export const requestPasswordReset500Schema = z.lazy(
  () => errorResponseSchema
) as unknown as z.ZodType<RequestPasswordReset500>

export const requestPasswordResetMutationRequestSchema = z.lazy(
  () => requestPasswordResetRequestSchema
) as unknown as z.ZodType<RequestPasswordResetMutationRequest>

export const requestPasswordResetMutationResponseSchema = z.lazy(
  () => requestPasswordReset200Schema
) as unknown as z.ZodType<RequestPasswordResetMutationResponse>
