/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from '../error-response'
import type { RegisterUserRequest } from '../register-user-request'
import type { RegisterUserSuccessResponse } from '../register-user-success-response'

/**
 * @description User successfully registered
 */
export type RegisterUser201 = RegisterUserSuccessResponse

/**
 * @description Invalid request data
 */
export type RegisterUser400 = ErrorResponse

/**
 * @description User with this email already exists
 */
export type RegisterUser409 = ErrorResponse

/**
 * @description Internal server error
 */
export type RegisterUser500 = ErrorResponse

export type RegisterUserMutationRequest = RegisterUserRequest

export type RegisterUserMutationResponse = RegisterUser201

export type RegisterUserMutation = {
  Response: RegisterUser201
  Request: RegisterUserMutationRequest
  Errors: RegisterUser400 | RegisterUser409 | RegisterUser500
}
