/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  RegisterUser400,
  RegisterUser409,
  RegisterUser500,
  RegisterUserMutationRequest,
  RegisterUserMutationResponse,
} from '../../__types__/api-v1-auth-register/register-user'
import fetch from '../../api-client/api-client.instance'
import type { Client, RequestConfig, ResponseErrorConfig } from '../../api-client/api-client.instance'

function getRegisterUserUrl() {
  const res = { method: 'POST', url: `/api/v1/auth/register` as const }
  return res
}

/**
 * @description Creates a new user account with email and password
 * @summary Register a new user
 * {@link /api/v1/auth/register}
 */
export async function registerUser(
  data: RegisterUserMutationRequest,
  config: Partial<RequestConfig<RegisterUserMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    RegisterUserMutationResponse,
    ResponseErrorConfig<RegisterUser400 | RegisterUser409 | RegisterUser500>,
    RegisterUserMutationRequest
  >({ method: 'POST', url: getRegisterUserUrl().url.toString(), data: requestData, ...requestConfig })
  return res.data
}
