/* eslint-disable no-alert, no-console */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { loginUserHandler } from './api-v1-auth-login-mocks/loginUserHandler'
import { refreshTokensHandler } from './api-v1-auth-refresh-mocks/refreshTokensHandler'
import { registerUserHandler } from './api-v1-auth-register-mocks/registerUserHandler'
import { requestPasswordResetHandler } from './api-v1-auth-request-password-reset-mocks/requestPasswordResetHandler'
import { resetPasswordHandler } from './api-v1-auth-reset-password-mocks/resetPasswordHandler'

export const handlers = [
  registerUserHandler(),
  loginUserHandler(),
  refreshTokensHandler(),
  requestPasswordResetHandler(),
  resetPasswordHandler(),
] as const
