/** @typedef  {import("prettier").Config} PrettierConfig */

/** @type { PrettierConfig | SortImportsConfig } */
const config = {
  endOfLine: 'lf',
  semi: false,
  singleQuote: true,
  tabWidth: 2,
  trailingComma: 'es5',
  jsxSingleQuote: true,
  bracketSpacing: true,
  printWidth: 120,
  proseWrap: 'always',
  plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
  importOrder: [
    '^react$',
    '^lucide-react$',
    '^react-hook-form$',
    '^lucide',
    '^date-fns$',
    '^axios',
    '^yup',
    '^ts-pattern',
    '^dayjs',
    '^@sentry',
    '^msw',
    '^mockjs',
    '^tailwind-variants$',
    '',
    '^@storybook/react',
    "^'msw-storybook-addon",
    '^vitest$',
    '@testing-library/react$',
    '',
    '<THIRD_PARTY_MODULES>',
    '',
    '<BUILTIN_MODULES>',
    '',
    '^(@app)(/.*)$',
    '',
    '^(@/pages)(/.*)$',
    '',
    '^(@/widgets)(/.*)$',
    '',
    '^(@/features)(/.*)$',
    '',
    '^(@/entities)(/.*)$',
    '',
    '^(@/shared)(/@types.*)$',
    '^(@/shared)(/__api__.*)$',
    '^(@/shared)(/constants.*)$',
    '^(@/shared)(/config.*)$',
    '^(@/shared)(/helpers.*)$',
    '^(@/shared)(/libraries.*)$',
    '^(@/shared)(/hooks.*)$',
    '^(@/shared)(/ui.*)$',
    '^(@/shared)(/assets.*)$',
    '',
    '^./*.types',
    '^./*.constants',
    '^./*.validation',
    '^./*.requests',
    '^./*.store',
    '^./*.helpers',
    '',
    '^[.]',
  ],
}

module.exports = config
