/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  RefreshTokens401,
  RefreshTokens500,
  RefreshTokensMutationRequest,
  RefreshTokensMutationResponse,
} from '../../__types__/api-v1-auth-refresh/refresh-tokens'
import fetch from '../../api-client/api-client.instance'
import type { Client, RequestConfig, ResponseErrorConfig } from '../../api-client/api-client.instance'

function getRefreshTokensUrl() {
  const res = { method: 'POST', url: `/api/v1/auth/refresh` as const }
  return res
}

/**
 * @description Generates new access and refresh tokens using a valid refresh token
 * @summary Refresh tokens
 * {@link /api/v1/auth/refresh}
 */
export async function refreshTokens(
  data: RefreshTokensMutationRequest,
  config: Partial<RequestConfig<RefreshTokensMutationRequest>> & { client?: Client } = {}
) {
  const { client: request = fetch, ...requestConfig } = config

  const requestData = data

  const res = await request<
    RefreshTokensMutationResponse,
    ResponseErrorConfig<RefreshTokens401 | RefreshTokens500>,
    RefreshTokensMutationRequest
  >({ method: 'POST', url: getRefreshTokensUrl().url.toString(), data: requestData, ...requestConfig })
  return res.data
}
