/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type {
  RefreshTokens200,
  RefreshTokens401,
  RefreshTokens500,
  RefreshTokensMutationRequest,
  RefreshTokensMutationResponse,
} from '../../__types__/api-v1-auth-refresh/refresh-tokens'
import { errorResponseSchema } from '../error-response-schema'
import { loginSuccessResponseSchema } from '../login-success-response-schema'
import { refreshTokenRequestSchema } from '../refresh-token-request-schema'

/**
 * @description Tokens successfully refreshed
 */
export const refreshTokens200Schema = z.lazy(() => loginSuccessResponseSchema) as unknown as z.ZodType<RefreshTokens200>

/**
 * @description Invalid refresh token
 */
export const refreshTokens401Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<RefreshTokens401>

/**
 * @description Internal server error
 */
export const refreshTokens500Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<RefreshTokens500>

export const refreshTokensMutationRequestSchema = z.lazy(
  () => refreshTokenRequestSchema
) as unknown as z.ZodType<RefreshTokensMutationRequest>

export const refreshTokensMutationResponseSchema = z.lazy(
  () => refreshTokens200Schema
) as unknown as z.ZodType<RefreshTokensMutationResponse>
