/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from '../error-response'
import type { LoginSuccessResponse } from '../login-success-response'
import type { RefreshTokenRequest } from '../refresh-token-request'

/**
 * @description Tokens successfully refreshed
 */
export type RefreshTokens200 = LoginSuccessResponse

/**
 * @description Invalid refresh token
 */
export type RefreshTokens401 = ErrorResponse

/**
 * @description Internal server error
 */
export type RefreshTokens500 = ErrorResponse

export type RefreshTokensMutationRequest = RefreshTokenRequest

export type RefreshTokensMutationResponse = RefreshTokens200

export type RefreshTokensMutation = {
  Response: RefreshTokens200
  Request: RefreshTokensMutationRequest
  Errors: RefreshTokens401 | RefreshTokens500
}
