/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type {
  RegisterUser201,
  RegisterUser400,
  RegisterUser409,
  RegisterUser500,
  RegisterUserMutationRequest,
  RegisterUserMutationResponse,
} from '../../__types__/api-v1-auth-register/register-user'
import { errorResponseSchema } from '../error-response-schema'
import { registerUserRequestSchema } from '../register-user-request-schema'
import { registerUserSuccessResponseSchema } from '../register-user-success-response-schema'

/**
 * @description User successfully registered
 */
export const registerUser201Schema = z.lazy(
  () => registerUserSuccessResponseSchema
) as unknown as z.ZodType<RegisterUser201>

/**
 * @description Invalid request data
 */
export const registerUser400Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<RegisterUser400>

/**
 * @description User with this email already exists
 */
export const registerUser409Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<RegisterUser409>

/**
 * @description Internal server error
 */
export const registerUser500Schema = z.lazy(() => errorResponseSchema) as unknown as z.ZodType<RegisterUser500>

export const registerUserMutationRequestSchema = z.lazy(
  () => registerUserRequestSchema
) as unknown as z.ZodType<RegisterUserMutationRequest>

export const registerUserMutationResponseSchema = z.lazy(
  () => registerUser201Schema
) as unknown as z.ZodType<RegisterUserMutationResponse>
