import { MEDIA_TASK_STATUS_HISTORY_MOCK_ROUTES, MEDIA_TASKS_MOCK_ROUTES } from './routes/media-tasks.mock.ts'
import { EXAMPLE_MOCK_ROUTE } from './routes/route.example.ts'

export const MOCK_HANDLERS = [
  ...EXAMPLE_MOCK_ROUTE,
  ...MEDIA_TASKS_MOCK_ROUTES,
  ...MEDIA_TASK_STATUS_HISTORY_MOCK_ROUTES,
]

export const STORYBOOK_MOCK_HANDLERS = {
  EXAMPLE_MOCK_ROUTE,
  MEDIA_TASKS_MOCK_ROUTES,
  MEDIA_TASK_STATUS_HISTORY_MOCK_ROUTES,
}
