/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ErrorResponse } from '../error-response'
import type { MessageSuccessResponse } from '../message-success-response'
import type { RequestPasswordResetRequest } from '../request-password-reset-request'

/**
 * @description Password reset email sent
 */
export type RequestPasswordReset200 = MessageSuccessResponse

/**
 * @description Invalid request data
 */
export type RequestPasswordReset400 = ErrorResponse

/**
 * @description User not found
 */
export type RequestPasswordReset404 = ErrorResponse

/**
 * @description Internal server error
 */
export type RequestPasswordReset500 = ErrorResponse

export type RequestPasswordResetMutationRequest = RequestPasswordResetRequest

export type RequestPasswordResetMutationResponse = RequestPasswordReset200

export type RequestPasswordResetMutation = {
  Response: RequestPasswordReset200
  Request: RequestPasswordResetMutationRequest
  Errors: RequestPasswordReset400 | RequestPasswordReset404 | RequestPasswordReset500
}
