/* eslint-disable no-alert, no-console */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw'

import type {
  RegisterUser400,
  RegisterUser409,
  RegisterUser500,
  RegisterUserMutationResponse,
} from '../../__types__/api-v1-auth-register/register-user'

export function registerUserHandlerResponse201(data: RegisterUserMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 201,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function registerUserHandlerResponse400(data: RegisterUser400) {
  return new Response(JSON.stringify(data), {
    status: 400,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function registerUserHandlerResponse409(data: RegisterUser409) {
  return new Response(JSON.stringify(data), {
    status: 409,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function registerUserHandlerResponse500(data: RegisterUser500) {
  return new Response(JSON.stringify(data), {
    status: 500,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function registerUserHandler(
  data?:
    | RegisterUserMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>)
) {
  return http.post(`/api/v1/auth/register`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 201,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
