/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { ErrorResponse } from '../__types__/error-response'

export const errorResponseSchema = z.object({
  message: z.string().describe('Error message describing what went wrong'),
  status: z.int().describe('HTTP status code'),
}) as unknown as z.ZodType<ErrorResponse>
