/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { LoginUserRequest } from '../__types__/login-user-request'

export const loginUserRequestSchema = z.object({
  email: z.email().describe('Email address of the user'),
  password: z.string().min(4).max(30).describe('User password'),
}) as unknown as z.ZodType<LoginUserRequest>
