/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { LoginSuccessResponse } from '../__types__/login-success-response'
import { tokenPairSchema } from './token-pair-schema'

export const loginSuccessResponseSchema = z.object({
  success: z.boolean().describe('Indicates whether the request was successful'),
  get data() {
    return tokenPairSchema
  },
}) as unknown as z.ZodType<LoginSuccessResponse>
