/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { MessageSuccessResponse } from '../__types__/message-success-response'

export const messageSuccessResponseSchema = z.object({
  success: z.boolean().describe('Indicates whether the request was successful'),
  data: z.string().describe('Success message'),
}) as unknown as z.ZodType<MessageSuccessResponse>
