/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { RefreshTokenRequest } from '../__types__/refresh-token-request'

export const refreshTokenRequestSchema = z.object({
  refreshToken: z.string().describe('Refresh token to generate a new token pair'),
}) as unknown as z.ZodType<RefreshTokenRequest>
