/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { RegisterUserSuccessResponse } from '../__types__/register-user-success-response'
import { registerUserResponseSchema } from './register-user-response-schema'

export const registerUserSuccessResponseSchema = z.object({
  success: z.boolean().describe('Indicates whether the request was successful'),
  get data() {
    return registerUserResponseSchema
  },
}) as unknown as z.ZodType<RegisterUserSuccessResponse>
