/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { RegisterUserRequest } from '../__types__/register-user-request'

export const registerUserRequestSchema = z.object({
  email: z.email().describe('Email address for the new user account'),
  password: z
    .string()
    .min(4)
    .max(30)
    .describe('Password for the new user account (minimum 4 characters, maximum 30 characters)'),
}) as unknown as z.ZodType<RegisterUserRequest>
