/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { RegisterUserResponse } from '../__types__/register-user-response'

export const registerUserResponseSchema = z.object({
  id: z.uuid().describe('Unique identifier of the created user'),
  email: z.email().describe('Email address of the user'),
  createdAt: z.iso.datetime({ offset: true }).describe('Timestamp when the user was created'),
  updatedAt: z.iso.datetime({ offset: true }).describe('Timestamp when the user was last updated'),
}) as unknown as z.ZodType<RegisterUserResponse>
