/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { RequestPasswordResetRequest } from '../__types__/request-password-reset-request'

export const requestPasswordResetRequestSchema = z.object({
  email: z.email().describe('Email address to send password reset instructions'),
}) as unknown as z.ZodType<RequestPasswordResetRequest>
