/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { ResetPasswordRequest } from '../__types__/reset-password-request'

export const resetPasswordRequestSchema = z.object({
  token: z.string().describe('Password reset token received via email'),
  newPassword: z
    .string()
    .min(4)
    .max(30)
    .describe('New password for the user account (minimum 4 characters, maximum 30 characters)'),
}) as unknown as z.ZodType<ResetPasswordRequest>
