/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

import type { TokenPair } from '../__types__/token-pair'

export const tokenPairSchema = z.object({
  accessToken: z.string().describe('JWT access token for API authentication'),
  refreshToken: z.string().describe('JWT refresh token for obtaining new access tokens'),
  tokenType: z.string().describe('Token type (always "Bearer")'),
  expiresIn: z.int().describe('Access token expiration time in seconds'),
}) as unknown as z.ZodType<TokenPair>
