/* eslint-disable no-alert, no-console */
/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { http } from 'msw'

import type {
  RefreshTokens401,
  RefreshTokens500,
  RefreshTokensMutationResponse,
} from '../../__types__/api-v1-auth-refresh/refresh-tokens'

export function refreshTokensHandlerResponse200(data: RefreshTokensMutationResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function refreshTokensHandlerResponse401(data: RefreshTokens401) {
  return new Response(JSON.stringify(data), {
    status: 401,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function refreshTokensHandlerResponse500(data: RefreshTokens500) {
  return new Response(JSON.stringify(data), {
    status: 500,
    headers: {
      'Content-Type': 'application/json',
    },
  })
}

export function refreshTokensHandler(
  data?:
    | RefreshTokensMutationResponse
    | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Response | Promise<Response>)
) {
  return http.post(`/api/v1/auth/refresh`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    })
  })
}
